version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: Amigo_Padaria
    restart: always
    environment:
      POSTGRES_USER: Zhiga
      POSTGRES_PASSWORD: zhiga123
      POSTGRES_DB: Amigo_Padaria_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
